"""Preference formation from micro comparisons."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Dict, List


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _parse_iso(ts: str) -> datetime:
    try:
        dt = datetime.fromisoformat(ts)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except Exception:
        return _now()


def _clip(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


class PreferenceFormer:
    """Derive stable dimension preferences and dynamic weights."""

    DIMENSIONS = [
        "scela_coverage",
        "consistency",
        "compliance",
        "shot_diversity",
        "mood_rhythm",
        "visual_precision",
        "platform_fit",
    ]
    MIN_COMPARISONS = 10
    WINDOW_DAYS = 30
    CONFIDENCE_DENY = 0.3
    DECAY = 0.98
    MIN_WEIGHT = 0.08
    MAX_WEIGHT = 0.22

    def __init__(self, logger=None):
        self.logger = logger

    def build_preferences(self, comparisons: List[Dict]) -> Dict[str, Dict]:
        """Build preferences from comparisons generated by MicroScorer.

        Each comparison entry is expected to include:
        - dimension
        - winner: "new" | "opponent" | "tie"
        - timestamp
        """
        if not comparisons:
            return {}

        cutoff = _now().timestamp() - self.WINDOW_DAYS * 86400
        by_dim: Dict[str, List[Dict]] = {}
        for c in comparisons:
            dim = c.get("dimension", "")
            if dim not in self.DIMENSIONS:
                continue
            ts = _parse_iso(str(c.get("timestamp", ""))).timestamp()
            if ts < cutoff:
                continue
            by_dim.setdefault(dim, []).append(c)

        prefs = {}
        for dim, rows in by_dim.items():
            n = len(rows)
            if n < self.MIN_COMPARISONS:
                continue
            wins = sum(1 for r in rows if r.get("winner") == "new")
            losses = sum(1 for r in rows if r.get("winner") == "opponent")
            ties = n - wins - losses
            win_rate = wins / n
            confidence = min(n / 20.0, 1.0)
            if confidence < self.CONFIDENCE_DENY:
                continue
            adjust = _clip((win_rate - 0.5) * 0.2, -0.1, 0.1)
            direction = "neutral"
            if win_rate > 0.55:
                direction = "prefer_high"
            elif win_rate < 0.45:
                direction = "prefer_low"
            prefs[dim] = {
                "dimension": dim,
                "direction": direction,
                "strength": round(abs(win_rate - 0.5) * 2, 3),
                "weight_adjustment": round(adjust, 4),
                "comparison_count": n,
                "confidence": round(confidence, 3),
                "win_rate": round(win_rate, 3),
                "wins": wins,
                "losses": losses,
                "ties": ties,
                "formed_at": _now().isoformat(),
            }
        return prefs

    def derive_weights(
        self,
        base_weights: Dict[str, float],
        preferences: Dict[str, Dict],
        days_since_formed: int = 0,
    ) -> Dict[str, float]:
        """Derive normalized active weights from base + preferences."""
        if not base_weights:
            base = 1.0 / len(self.DIMENSIONS)
            base_weights = {d: base for d in self.DIMENSIONS}

        raw = {}
        for dim, base_w in base_weights.items():
            pref = preferences.get(dim)
            if not pref:
                raw_w = base_w
            else:
                decay = self.DECAY ** max(0, days_since_formed)
                raw_w = base_w + pref["weight_adjustment"] * pref["confidence"] * decay
            raw[dim] = _clip(raw_w, self.MIN_WEIGHT, self.MAX_WEIGHT)

        total = sum(raw.values()) or 1.0
        normalized = {k: (v / total) for k, v in raw.items()}
        # Keep exact sum=1.0 by compensating final dimension.
        if self.DIMENSIONS:
            head = self.DIMENSIONS[:-1]
            last = self.DIMENSIONS[-1]
            head_sum = sum(normalized.get(d, 0.0) for d in head)
            normalized[last] = max(0.0, 1.0 - head_sum)
        return normalized
